apiVersion: v1
kind: Secret
metadata:
  name: edgecontroller
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgecontroller
stringData:
  rootCA.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFizCCA3OgAwIBAgIJAMsB1LBvlD4xMA0GCSqGSIb3DQEBCwUAMFwxCzAJBgNV
    BAYTAkNOMREwDwYDVQQIDAhaaGVqaWFuZzERMA8GA1UEBwwISGFuZ3pob3UxETAP
    BgNVBAoMCEt1YmVFZGdlMRQwEgYDVQQDDAtrdWJlZWRnZS5pbzAeFw0yMDAzMjUw
    MjIwMzBaFw0zMDAzMjMwMjIwMzBaMFwxCzAJBgNVBAYTAkNOMREwDwYDVQQIDAha
    aGVqaWFuZzERMA8GA1UEBwwISGFuZ3pob3UxETAPBgNVBAoMCEt1YmVFZGdlMRQw
    EgYDVQQDDAtrdWJlZWRnZS5pbzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
    ggIBAJw7EbeiTZtTiol36RxdpjVcqcoEgQMf3K9tWWPV1u8ZWitYXl8OhAKOCf8H
    WShwukVzTeYH4xQvk7UDAZp6xCftQoNpTh9YC/7qC9lTdqEKBBd0ZR1XvpmsaLgH
    4tlT9jdptDmpKfgkuzUjGP2vV2TO++uvx9nd2aP1JfbLN+HOK5A0irNKVz7VVwLK
    QOMja+wL2XTi9JliCEzkN0fEh/hcFK/NtebS6L2FG8UJAAnWxss8wx+jiXRKhqxB
    8m3/Lbgz3og70BU/ao9Ci53I6stJjvuEyfHiDPtzXIr5U652H/Xcfj6at5xPZEsB
    UjXH/kmd16beyuUxmdoJLmitOw6dFkRe/KMXp4ZOVrznZyRR4iXuv3EuWqOmgdSL
    L18+r5axuKRuJ3I/PMpEwDSGqc/sAy5xAUfFne6AFiNwF+NsvYxHvIxJtHkgJJD+
    yImCKV+rEurheiCHogD/lAJUCrN1iGTxuZ3sr8zbevV5Ww6tT9jbbPLXOD0q2Xk2
    o6fA4aUzq/R+cyG/xgO0bYwQFFlny9uIlqGBiddWEciPF41MCHTVGMSzkCb2y906
    VdaKKgSmCae+iXTfYj8cZ2ZRZsLOhE0JCXZfWN382PwaG1oF9+GfFQIicYGjvrtG
    D+bugNTu7uj/RY6Gu4UW4ULSkwQ7Y9lo+kKRACBmzsF+Fc9/AgMBAAGjUDBOMB0G
    A1UdDgQWBBT8unsIA81LyRznFKLfYlbj8QW+nDAfBgNVHSMEGDAWgBT8unsIA81L
    yRznFKLfYlbj8QW+nDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQB8
    t9TqOhVjQkV3XlXbu3hOEDaFQ07+X7pMEpVPJgtYnyyywqhQobDtdguOnYqbWngD
    CQIyTKRSb2adI8UhtQcyPPzMiJXxskDaA7418AWka9dDM/GpQ9f8/d7KX9vrEmAE
    UBlvRYbDSOBOyueg06huvjIUikXZZJxvvUQSoMPt3AZthK/lyRb/zYxZvaMV04PA
    NUMj0novBb5DFDsMX6LjFgYt/vDe8NyIgEq2XQxT9167gg1bJ48+7yncV6ypCJnr
    pwQTIvO47pCjMifEPZyAZec15EIflTikrLzOYe99NOukzhv8wCYtHEm8BLzNniMg
    Y140c75rAMxZw8FC53I5fqPxw5BW1gxXLS+7J85DC6NtnKo9EPGEkR6VWUViBLvE
    3ESBhqbvZdldJqAyuYnwYtZX2ida/jCcB483/Jt/eXBNG2rrdewE+OzFG1DlDBTA
    ALWb4qKbjxy84KRBNHLDocNgKecXLt2feNXKdjx66n6OkZvGLApzYE0m8d8WQOZ9
    UXRi7IyoZi3dUWC6mFMbd2/e5gskHZzmWjJxyl29tE9OFr5XOX30L2dNJzUHRDtf
    FkGZoUEmvFgRbzue3MGBnYnNXN9O/DMOW25gi9MGdgp5tJwsCSLvpzq4xHve1iad
    XbaIambURIxpdhBZZzcq7pAFtV9kHmPKbKqa4aBNyw==
    -----END CERTIFICATE-----
  edge.crt: |
    -----BEGIN CERTIFICATE-----
    MIIENDCCAhwCCQDUIKgEHz02VTANBgkqhkiG9w0BAQsFADBcMQswCQYDVQQGEwJD
    TjERMA8GA1UECAwIWmhlamlhbmcxETAPBgNVBAcMCEhhbmd6aG91MREwDwYDVQQK
    DAhLdWJlRWRnZTEUMBIGA1UEAwwLa3ViZWVkZ2UuaW8wHhcNMjAwMzI1MDIyMDUy
    WhcNMjEwMzI1MDIyMDUyWjBcMQswCQYDVQQGEwJDTjERMA8GA1UECAwIWmhlamlh
    bmcxETAPBgNVBAcMCEhhbmd6aG91MREwDwYDVQQKDAhLdWJlRWRnZTEUMBIGA1UE
    AwwLa3ViZWVkZ2UuaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDK
    s6nUTpcZCExTK7WhN4gEqt5pDVBqbNu8SqFp2RJqTQoxeGR9WxfN0/HGL7cQhLnj
    Kv1LRyiQ8QGWJNgo3NCj1Bbp2vUg+yU35sdmPrZaZ+LpUIidoeJXOt+8wLc4qFuI
    iwv4b03V+Qal2ca1adxLfNslXbNP4NIwKYuD8UCEVDpIH4MDMbJeTYjYCVr+YM3a
    kIR5WQP2M89ZOyKAfeD7XixUsr6k6CmzDaC3OqMma3HUqzddZlSEFbdKKwKiINOr
    26JDPesqZHKgoGVFAiZdHDZCeLqhyiN6AKdIIIilZV4cr9alVrpmW/R7mWXt3uXI
    x4QkeB9zFoWMQ3F4u+mXAgMBAAEwDQYJKoZIhvcNAQELBQADggIBAG3WnWTgzWva
    DISgJD+TJB+bB7EpLWOfEkclnV8KmAVe6KWOU4xU2dlKNgLzazNCh7qCVZZFu21e
    NKstNCFmxPzTBnbyUeydyprE0UtcqfWvOPnkDcqpuQT05zF0kaSgYlvfFKm1wXtH
    5hbhBXZBf24jf+2LbJjNUaD9aYksTGBLE5GIi2WkUUHXmxCQLFT6IjJ/Qt6kXb3v
    apkhPmuIefwNR7H1FNID4IGRSYi9hLzphD7R0HsOsIVOKPgsA1H614zwbIpfV8nV
    ZBBOO4/a1aGr3c5nbbdbSTe22XQHOcxBvA7Q14MCHJP5v8CSdmNjgT6XWbwgIKhC
    3ULNf5SKNWuinNgFyPjIv28rAEqhJVXHGo3jNaBkvV5t+/mTgnpSlRGSYZi5YLiR
    Mui6qws+4B85e4mmY8c15+LB5rtC6j84VhfG4M7FSRei+VwuYEKUiExj37ntkxrS
    UKRExwCbDjBihq7liXvvxq2irqAVxlIw5ByAhemh9ZwCcHEx2Lhv9p8bWdz8px0C
    IlYMRCTWXpe09Xnvl8q8bFgwhRerJpZoF5jSz7N6s0XJbJXc98qtc8ImMjJv7A1i
    ze1Pf/CKgkP+ZJGjmb1eoDTQ576hevbqPIXehV4MFp5hXp5ZpUEXHXZxk73x6Y6+
    ybd/vndLILmIFOXyqtw+EGaZSmIvQGT6
    -----END CERTIFICATE-----
  edge.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAyrOp1E6XGQhMUyu1oTeIBKreaQ1QamzbvEqhadkSak0KMXhk
    fVsXzdPxxi+3EIS54yr9S0cokPEBliTYKNzQo9QW6dr1IPslN+bHZj62Wmfi6VCI
    naHiVzrfvMC3OKhbiIsL+G9N1fkGpdnGtWncS3zbJV2zT+DSMCmLg/FAhFQ6SB+D
    AzGyXk2I2Ala/mDN2pCEeVkD9jPPWTsigH3g+14sVLK+pOgpsw2gtzqjJmtx1Ks3
    XWZUhBW3SisCoiDTq9uiQz3rKmRyoKBlRQImXRw2Qni6ocojegCnSCCIpWVeHK/W
    pVa6Zlv0e5ll7d7lyMeEJHgfcxaFjENxeLvplwIDAQABAoIBAGTlCtqXh9Q48izP
    6+dkSbrxBiXKL8XZi4Jsr22NVAI/eJxpLbPL3Mxh+81HQNrjBdfSNSP8Nm/21nBS
    xJmKV/vD/OfISg1xlPP/Vi9JdeEIJsU1hdrYkl4S+vzr/AcinfUYKQwu8tJX0vxI
    qwTvvWyBqF8wBanz4QuCEmTJd/ClTVmplzgDF9GOfnqRZj4USWvI3x6PLFI9oGuz
    pwpqqky41bGkisxn1odtTKFJQryIwZg05yaZhuIzPGMQPG4MSVe3ihFxmdMei7PQ
    Q5XiO+hOo6G0UVlvp0YmuJpooYIzG51HxM4qdOXDg4CCAi/+huaQyUM97QW2I5KC
    RBiIimkCgYEA5TStrXdwvU5QU+UCxHWUpyhCfc4FJEmYvYqIhNRMkhwXttusgDId
    7Rit2hf2aOAiwMjEMK3pF8fTvddVn8g9fRYEZtvSUNcgFNl9Nwfx9YcJIWksCnbx
    z0SxsyayskyLAmSJ2vFCM95Wr7Qu6mXju4Xv6kvc7tQM6pAlC4Z/fjsCgYEA4mXQ
    jI65vx69hb2vkvvDH1OyypV2LU7vmY/yZ3HGzyHMlq402RZ89fy/F/mGGeF98/TR
    hUXck0Irhn43NjYNwIN8Y4GCOcTwK3Cb4Az5Uv44F3mg6sqp3W1JQBJiFwV3XGYn
    DMHLwNSIUL8d7jmx1D/g0sfvqxxvSzMx+TfFAFUCgYBQSsnkkIjP6BU/rmPvynjO
    rc3NIFSwx49YJqV4Up6YOHseNYoSRnwxSInucqKBTrMd8ba4jtOu3vOP91Upag4Q
    OZxFJBBi/VlhtGam1oOuTSWnrJ4e9Ff1Ec1mQtIqn6G6rtmT9xwH64VWe7pLpnHG
    iT7oRrcYevQjX2d6yBz1bQKBgQDL1v4Jv+vv736Wry4o+fM5/oMpMZ8gtkS2j8ui
    Zeep0XXCaYF9wGislm9755ddMBDWmSQYiclK8TX9NyEA93Q0VG6nrRCScQYJJq/B
    8AyANBJO2J0RKX39twtP2/1jWvGYSQV5z/djXDiL8zfAqUO6pfUH8yqQdt6h56tk
    B1mhrQKBgCrWqlS23nHWgkg+RQJ8UiRu4sex2ir+2H0iCyKW1NSzgvCadngJybjn
    gYgP97L/BBmXYnFwkUJd22gowzJBibLhwbIzssAbRgaI9VUPVAxnSc6W6HzBJbuW
    ffvvs298sBoPR+gxyz81Oc6BtvnE9j3lXXf7dNnT8UmgFxHPZ+H2
    -----END RSA PRIVATE KEY-----

