apiVersion: v1
kind: Service
metadata:
  name: edgecontroller
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgecontroller
spec:
  type: NodePort
  ports:
  - port: 10000
    name: cloudhub
    nodePort: 31000
  selector:
    k8s-app: kubeedge
    kubeedge: edgecontroller
