apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgenode1
  namespace: kubeedge
  labels:
    k8s-app: kubeedge
    kubeedge: edgenode
spec:
  selector:
    matchLabels:
      k8s-app: kubeedge
      kubeedge: edgenode
  template:
    metadata:
      labels:
        k8s-app: kubeedge
        kubeedge: edgenode
    spec:
      containers:
      - name: edgenode
        securityContext:
          privileged: true
        image: prodan/edgecore:v1.2.1-centos7
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: certs
          mountPath: /etc/kubeedge
        - name: conf
          mountPath: /etc/kubeedge/config
        resources: 
            requests: 
                cpu: 20m 
                memory: 512Mi 
      restartPolicy: Always
      serviceAccount: edgecontroller
      serviceAccountName: edgecontroller
      volumes:
      - name: conf
        configMap:
          name: edgenodeconf
      - name: certs
        secret:
          secretName: edgecontroller
          items:
          - key: edge.crt
            path: certs/edge.crt
          - key: edge.key
            path: certs/edge.key
          - key: rootCA.crt
            path: ca/rootCA.crt
